dummy_e/config/routes.rb
DummyE::Engine.routes.draw do
  resources :articles do
    resources :comments
  end
end

dummy_e/app/models/dummy_e/article.rb
module DummyE
  class Article < ApplicationRecord
    has_many :comments

    def summary
      "#{title}"
    end
  end
end

dummy_e/app/models/dummy_e/comment.rb
module DummyE
  class Comment < ApplicationRecord
  end
end

dummy_e/app/controllers/dummy_e/articles_controller.rb
#require_dependency "dummy_e/application_controller"

module DummyE
  class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles
    def index
      @articles = Article.all
    end

    # GET /articles/1
    def show
    end

    # GET /articles/new
    def new
      @article = Article.new
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to @article, notice: 'Article was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /articles/1
    def update
      if @article.update(article_params)
        redirect_to @article, notice: 'Article was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /articles/1
    def destroy
      @article.destroy
      redirect_to articles_url, notice: 'Article was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :text, :article_id)
    end
  end
end

dummy_e/app/controllers/dummy_e/comments_controller.rb
#require_dependency "dummy_e/application_controller"

module DummyE
  class CommentsController < ApplicationController
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      flash[:notice] = 'Comment has been created!'
      redirect_to articles_path
    end

    private

    def comment_params
      params.require(:comment).permit(:text)
    end
  end
end

dummy_e/app/helpers/dummy_e/articles_helper.rb
module DummyE
  module ArticlesHelper
  end
end

dummy_e/app/helpers/dummy_e/comments_helper.rb
module DummyE
  module CommentsHelper
  end
end

dummy_e/app/views/dummy_e/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

dummy_e/app/views/dummy_e/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

dummy_e/app/views/dummy_e/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

dummy_e/app/views/dummy_e/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

dummy_e/app/views/dummy_e/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Comments:</strong>
  <% @article.comments.each do |el| %>
    <p> <%= el.text %> </p>
  <% end %>
</p>

<%= render "dummy_e/comments/form" %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

dummy_e/app/views/dummy_e/comments/_form.html.erb
<h3>New comment</h3>
<%= form_with(model: [@article, @article.comments.build], local: true) do |form| %>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <%= form.submit %>
<% end %>